name = "Elf"
uuid = "4072d141-89ef-40eb-af00-2058da74fdbd"
authors = ["sasuseso <sinai471530@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
